### ISSUE TITLE
Beep enabled/disabled in ble notification data

### ISSUE THREAD

**Issue by mm108** [zh2x/BCI_Protocol#1]
A quick question; the Berry Med Pulse Oximeter has the beep sound that can be turned on/off by pressing the button the Pulse Oximeter. When the Beep is turned on a small speaker icon appears on the Pulse Oximeter. Is this information (whether beep enabled/disabled) is also available in the ble notification data? I was thinking that it was the 6th bit of 1st byte but then
that doesn't seem to work.

**Comment by zh2x** [comment]
Yes, the "Pulse Beep" bit indicates that one pulse peak detected.

**Comment by mm108** [comment]
Ok, thank you.
